SearchSpace:
  type: LayersBased
  layers_types: [Conv2d, MaxPool2d, Dropout, ReLU]
  layers_count: [5, 7]
  channels: [3, 5]
  kernel: [2, 3]
  padding: [0, 1, 2]
  last_hid_mlp: [0, 50, 100]
  dropout_rates: [0.1, 0.3]

SearchStrategy:
  type: RandomSearch
  nbr_iterations: 4

ValidationStrategy:
  type: FullTraining
  optimizer: Adam
  optimizer_params: {lr: 0.1}
  epochs: 15
  metrics: [acc_val]
  trn_data: {url: data/mnist_train.csv, batch: 30}
  val_data: {url: data/mnist_test.csv, batch: 40}